login_page:
    resource: "@CoreBundle/Resources/config/routing.yml"
    prefix: /

sms:
    resource: "@SmsBundle/Resources/config/routing.yml"
    prefix:   /sms

request_redirect:
    path: /request
    defaults: { _controller: AdminBundle:EmployeeRequest:requestRedirect }

admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /main

_security_check:
    pattern: /login_check

logout:
   pattern: /logout

error403:
    pattern: /403
